### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by aksiksi** [MAVProxyUser/SilverPushUnmasked#2]
I'm a grad student who's planning on developing an app that can detect when SilverPush (or similar) technology is being used for targeted advertising. This will be for a course project, at least initially. If I can get a paper out of it (unlikely!), I will be sure to let you know and we can figure something out.

So is it alright if I use some of the resources you've added to the repo as a starting point?

Thanks.

**Comment by MAVProxyUser** [comment]
By all means do... also check my Twitter account http://www.twitter.com/d0tslash and the #SilverPush hash tag I used while discussing this topic.
